# Site settings
title: 'John Koury, Architect'
company_name: 'John Koury, Architect'
baseurl: ''
imagebase: '/dist/images'

collections_dir: collections
collections:
  people:
    name: 'People'
    output: true
    order: 0
    img: 'slides/mckean/mckean1.jpg'
  process:
    name: 'Process'
    output: true
    order: 1
    img: 'slides/celgard/celgard1.png'
  articles:
    name: 'Articles'
    output: false
    order: 2

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'Gemfile',
  'Gemfile.lock',
  'assets/'
]
languages: ['en']
