# Site settings
title: 'John Koury, Architect'
company_name: 'John Koury, Architect'
baseurl: ''
imagebase: '/dist/images'

collections_dir: collections
collections:
  industrialrandd:
    name: 'Industrial/ Research and Development'
    output: true
    order: 0
  coldstoragedistribution:
    name: 'Cold Storage'
    output: true
    order: 1
  foodprocess:
    name: 'Food Process'
    output: true
    order: 2
  medicaloffice:
    name: 'Medical Office'
    output: true
    order: 3
  office:
    name: 'Office'
    output: true
    order: 4
  athletic:
    name: 'Athletic'
    output: true
    order: 5
  residential:
    name: 'Residential'
    output: true
    order: 6
  articles:
    name: 'Articles'
    output: true
    order: 7

source: _src

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'assets/'
]
languages: ['en']
